# Generated by Django 2.0.1 on 2018-01-25 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_remove_messageboard_messengerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=20)),
                ('retopic', models.CharField(max_length=50)),
                ('recontent', models.CharField(blank=True, max_length=1000)),
                ('repostdate', models.DateTimeField(auto_now_add=True)),
                ('articleid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='message.MessageBoard')),
            ],
            options={
                'db_table': 'replyboard',
            },
        ),
    ]
