# Generated by Django 2.0.1 on 2018-01-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companydata',
            fields=[
                ('comstocknum', models.IntegerField(primary_key=True, serialize=False)),
                ('ccompanyname', models.CharField(max_length=50)),
                ('comaddress', models.CharField(max_length=200)),
                ('comcode', models.CharField(max_length=9)),
                ('comceo', models.CharField(max_length=50)),
                ('comphone', models.CharField(max_length=20)),
                ('comset', models.DateField()),
                ('comontwse', models.DateField()),
                ('comhttp', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PL105Q1',
            fields=[
                ('comstocknum', models.IntegerField(primary_key=True, serialize=False)),
                ('ccompanyname', models.CharField(max_length=50)),
                ('comrev5q1', models.FloatField()),
                ('comgp5q1', models.FloatField()),
                ('comnp5q1', models.FloatField()),
                ('comnbt5q1', models.FloatField()),
                ('comnat_5q1', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PL105Q2',
            fields=[
                ('comstocknum', models.IntegerField(primary_key=True, serialize=False)),
                ('ccompanyname', models.CharField(max_length=50)),
                ('comrev5q2', models.FloatField()),
                ('comgp5q2', models.FloatField()),
                ('comnp5q2', models.FloatField()),
                ('comnbt5q2', models.FloatField()),
                ('comnat_5q2', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PL105Q3',
            fields=[
                ('comstocknum', models.IntegerField(primary_key=True, serialize=False)),
                ('ccompanyname', models.CharField(max_length=50)),
                ('comrev5q3', models.FloatField()),
                ('comgp5q3', models.FloatField()),
                ('comnp5q3', models.FloatField()),
                ('comnbt5q3', models.FloatField()),
                ('comnat_5q3', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PL105Q4',
            fields=[
                ('comstocknum', models.IntegerField(primary_key=True, serialize=False)),
                ('ccompanyname', models.CharField(max_length=50)),
                ('comrevq4', models.FloatField()),
                ('comgpq4', models.FloatField()),
                ('comnpq4', models.FloatField()),
                ('comnbtq4', models.FloatField()),
                ('comnat_5q4', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PL106Q1',
            fields=[
                ('comstocknum', models.IntegerField(primary_key=True, serialize=False)),
                ('ccompanyname', models.CharField(max_length=50)),
                ('comrevq1', models.FloatField()),
                ('comgpq1', models.FloatField()),
                ('comnpq1', models.FloatField()),
                ('comnbtq1', models.FloatField()),
                ('comnat_q1', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PL106Q2',
            fields=[
                ('comstocknum', models.IntegerField(primary_key=True, serialize=False)),
                ('ccompanyname', models.CharField(max_length=50)),
                ('comrevq2', models.FloatField()),
                ('comgpq2', models.FloatField()),
                ('comnpq2', models.FloatField()),
                ('comnbtq2', models.FloatField()),
                ('comnat_q2', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PL106Q3',
            fields=[
                ('comstocknum', models.IntegerField(primary_key=True, serialize=False)),
                ('ccompanyname', models.CharField(max_length=50)),
                ('comrevq3', models.FloatField()),
                ('comgpq3', models.FloatField()),
                ('comnpq3', models.FloatField()),
                ('comnbtq3', models.FloatField()),
                ('comnat_q3', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Stockclass',
            fields=[
                ('stocknum', models.IntegerField(primary_key=True, serialize=False)),
                ('companyname', models.CharField(max_length=50)),
                ('companyclass', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'stockclass',
            },
        ),
    ]
