# Generated by Django 2.0.1 on 2018-01-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bs103',
            fields=[
                ('comstocknum', models.IntegerField(primary_key=True, serialize=False)),
                ('ccompanyname', models.CharField(max_length=50)),
                ('r10301', models.FloatField()),
                ('r10302', models.FloatField()),
                ('r10303', models.FloatField()),
                ('r10304', models.FloatField()),
                ('r10305', models.FloatField()),
                ('r10306', models.FloatField()),
                ('r10307', models.FloatField()),
                ('r10308', models.FloatField()),
                ('r10309', models.FloatField()),
                ('r10310', models.FloatField()),
                ('r10311', models.FloatField()),
                ('r10312', models.FloatField()),
                ('r10313', models.FloatField()),
                ('r10314', models.FloatField()),
                ('r10315', models.FloatField()),
                ('r10316', models.FloatField()),
                ('r10317', models.FloatField()),
                ('r10318', models.FloatField()),
                ('r10319', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='bs104',
            fields=[
                ('comstocknum', models.IntegerField(primary_key=True, serialize=False)),
                ('ccompanyname', models.CharField(max_length=50)),
                ('r10401', models.FloatField()),
                ('r10402', models.FloatField()),
                ('r10403', models.FloatField()),
                ('r10404', models.FloatField()),
                ('r10405', models.FloatField()),
                ('r10406', models.FloatField()),
                ('r10407', models.FloatField()),
                ('r10408', models.FloatField()),
                ('r10409', models.FloatField()),
                ('r10410', models.FloatField()),
                ('r10411', models.FloatField()),
                ('r10412', models.FloatField()),
                ('r10413', models.FloatField()),
                ('r10414', models.FloatField()),
                ('r10415', models.FloatField()),
                ('r10416', models.FloatField()),
                ('r10417', models.FloatField()),
                ('r10418', models.FloatField()),
                ('r10419', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='bs105',
            fields=[
                ('comstocknum', models.IntegerField(primary_key=True, serialize=False)),
                ('ccompanyname', models.CharField(max_length=50)),
                ('r10501', models.FloatField()),
                ('r10502', models.FloatField()),
                ('r10503', models.FloatField()),
                ('r10504', models.FloatField()),
                ('r10505', models.FloatField()),
                ('r10506', models.FloatField()),
                ('r10507', models.FloatField()),
                ('r10508', models.FloatField()),
                ('r10509', models.FloatField()),
                ('r10510', models.FloatField()),
                ('r10511', models.FloatField()),
                ('r10512', models.FloatField()),
                ('r10513', models.FloatField()),
                ('r10514', models.FloatField()),
                ('r10515', models.FloatField()),
                ('r10516', models.FloatField()),
                ('r10517', models.FloatField()),
                ('r10518', models.FloatField()),
                ('r10519', models.FloatField()),
            ],
        ),
    ]
