# Generated by Django 2.0.1 on 2018-01-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20180122_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bs103',
            name='r10301',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs103',
            name='r10302',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs103',
            name='r10303',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs103',
            name='r10304',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs103',
            name='r10305',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs103',
            name='r10306',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs103',
            name='r10307',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs103',
            name='r10308',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs103',
            name='r10309',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs103',
            name='r10310',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs103',
            name='r10311',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs103',
            name='r10312',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs103',
            name='r10313',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs103',
            name='r10314',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs103',
            name='r10315',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs103',
            name='r10316',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs103',
            name='r10317',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs103',
            name='r10318',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs103',
            name='r10319',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs104',
            name='r10401',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs104',
            name='r10402',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs104',
            name='r10403',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs104',
            name='r10404',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs104',
            name='r10405',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs104',
            name='r10406',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs104',
            name='r10407',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs104',
            name='r10408',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs104',
            name='r10409',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs104',
            name='r10410',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs104',
            name='r10411',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs104',
            name='r10412',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs104',
            name='r10413',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs104',
            name='r10414',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs104',
            name='r10415',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs104',
            name='r10416',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs104',
            name='r10417',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs104',
            name='r10418',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs104',
            name='r10419',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs105',
            name='r10501',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs105',
            name='r10502',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs105',
            name='r10503',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs105',
            name='r10504',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs105',
            name='r10505',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs105',
            name='r10506',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs105',
            name='r10507',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs105',
            name='r10508',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs105',
            name='r10509',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs105',
            name='r10510',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs105',
            name='r10511',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs105',
            name='r10512',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs105',
            name='r10513',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs105',
            name='r10514',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs105',
            name='r10515',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs105',
            name='r10516',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs105',
            name='r10517',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs105',
            name='r10518',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bs105',
            name='r10519',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
