# Generated by Django 2.0.1 on 2018-01-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('useremail', models.EmailField(blank=True, max_length=100)),
                ('trackednumber', models.IntegerField()),
                ('trackedconame', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'membertrack',
            },
        ),
    ]
